### ISSUE TITLE
FabledSkyblock

### ISSUE THREAD

**Issue by vGlitch** [ezzerland/InstantItemPickUp#1]
Not sure how it's caused. Or how to fix.
When on FabledSkyblock(A skyblock plugin) Islands,  dropping items instantly deletes the item. Doesn't even give me time to see the item. I asked the team of the plugin, and one of the trial staff told me to delete this and see if it works, and it did. Unfortunate deletion. There are also 0 logs generated before I deleted.

**Comment by ezzerland** [comment]
I don't have FabledSkyblock but I can try and guestimate the issue.

This happens when players drop items or when Skyblock generates items? Could you possibly make a short video displaying what happens?

Edit - ALso, what server version are you running?

**Comment by vGlitch** [comment]
It's whenever I'm in skyblock worlds that this happens. https://gyazo.com/d5f32f0b9758c30fbdd45b4f56b8a117
This link is what I showed the developer/helpers.

**Comment by ezzerland** [comment]
Does this only happen when you are in creative mode?
And what server version?

**Comment by vGlitch** [comment]
Server version 1.12.2 - 
And it did both survival and creative.

**Comment by ezzerland** [comment]
[Checking their code](https://gitlab.com/Songoda/fabledskyblock/blob/development/FabledSkyBlock/Core/src/main/java/me/goodandevil/skyblock/listeners/Item.java ), I decided to test if a cancelled PlayerDropItemEvent still issues an ItemSpawnEvent, and it does. (odd, because no item is spawned).

Try [this release](https://github.com/ezzerland/InstantItemPickUp/raw/master/build/InstantItemPickUp.jar), and let me know if the issue persists.

**Comment by ezzerland** [comment]
Assuming that build fixed it since no response.
